// Mocks generated by Mockito 5.4.4 from annotations
// in orange_player/test/application/playlists/playlists_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:orange_player/domain/repositories/playlists_repository.dart'
    as _i2;
import 'package:orange_player/domain/usecases/playlists_usecases.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePlaylistsRepository_0 extends _i1.SmartFake
    implements _i2.PlaylistsRepository {
  _FakePlaylistsRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PlaylistsUsecases].
///
/// See the documentation for Mockito's code generation for more information.
class MockPlaylistsUsecases extends _i1.Mock implements _i3.PlaylistsUsecases {
  MockPlaylistsUsecases() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.PlaylistsRepository get playlistsRepository => (super.noSuchMethod(
        Invocation.getter(#playlistsRepository),
        returnValue: _FakePlaylistsRepository_0(
          this,
          Invocation.getter(#playlistsRepository),
        ),
      ) as _i2.PlaylistsRepository);

  @override
  _i4.Future<List<dynamic>> getPlaylistsUsecase() => (super.noSuchMethod(
        Invocation.method(
          #getPlaylistsUsecase,
          [],
        ),
        returnValue: _i4.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i4.Future<List<dynamic>>);
}
