// Mocks generated by Mockito 5.4.4 from annotations
// in orange_player/test/infrastructure/datasource/audiofiles_datasources_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:io' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:orange_player/infrastructure/datasources/audiofiles_datasources.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [AudioFilesDataSources].
///
/// See the documentation for Mockito's code generation for more information.
class MockAudioFilesDataSources extends _i1.Mock
    implements _i2.AudioFilesDataSources {
  MockAudioFilesDataSources() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.FileSystemEntity>> getAudioFiles() => (super.noSuchMethod(
        Invocation.method(
          #getAudioFiles,
          [],
        ),
        returnValue: _i3.Future<List<_i4.FileSystemEntity>>.value(
            <_i4.FileSystemEntity>[]),
      ) as _i3.Future<List<_i4.FileSystemEntity>>);
}
